// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	private String clientName;
	/**
	 * 
	 */
	private String phone;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	private Training trainingEvent;
	/**
	 * 
	 */
	public Training[] training;

	/**
	 * 
	 */
	public void contactInfo() {
	}

	/**
	 * 
	 * @param training 
	 */
	public void cancelTraining(Training training) {
	}

	/**
	 * 
	 * @param trainingType 
	 * @param trainingDate 
	 */
	public void requestTraining(TrainingType trainingType, String trainingDate) {
	}

	/**
	 * 
	 * @param trainingName 
	 */
	public void changeTrainingDetails(Training trainingName) {
	}
}
