// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
import java.util.*;
public class Client{
	/**
	 * 
	 */
	private String clientName;
	/**
	 * 
	 */
	private String phone;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	//private Training trainingEvent = new Training();
	/**
	 * 
	 */
	public List<Training> trainings = new ArrayList<>();

	/**
	 * 
	 */
	public void contactInfo() {
	}

	/**
	 * 
	 * @param training 
	 */
	public void cancelTraining(Training training) {
	}

	/**
	 * 
	 * @param trainingType 
	 * @param trainingDate 
	 */
	public void requestTraining(TrainingType trainingType, String trainingDate) {
	}

	/**
	 * 
	 * @param trainingName 
	 */
	public void changeTrainingDetails(Training trainingName) {
	}
}
