// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
import java.util.*;
public class Client{
	/**
	 * 
	 */
	private String clientName;
	/**
	 * 
	 */
	private String phone;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	private Training trainingEvent = new Training();
	/**
	 * 
	 */
	public List<Training> trainings = new ArrayList<>();

	/**
	 * 
	 */
	Client(){}
	Client(String clientName, String phone, String email){
		this.clientName = clientName;
		this.phone = phone;
		this.email = email;
	}

	public void contactInfo() {
		System.out.println("Nume: " + this.clientName);
		System.out.println("Phone: " + this.phone);
		System.out.println("Email: " + this.email);
	}

	/**
	 * 
	 * @param training 
	 */
	public void cancelTraining(Manager manager, String eventName, String date) {
		for(int i = 0; i < this.trainings.size(); i++){
			if(this.trainings.get(i).getEventName().equals(eventName) && this.trainings.get(i).getEventDate().equals(date)){
				//Am pus un obiect de tip manager pentru a putea elimina si din lista managerului 
			}
		}
	}

	/**
	 * 
	 * @param trainingType 
	 * @param trainingDate 
	 */
	public void requestTraining(TrainingType trainingType, String trainingDate) {

	}

	/**
	 * 
	 * @param trainingName 
	 */
	public void changeTrainingDetails(Training trainingName) {
	}
}
