// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
import java.util.*;
/************************************************************/
/**
 * 
 */
public class Manager {
	/**
	 * 
	 */
	private String managerName;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	private String phone;
	/**
	 * 
	 */
	private Training trainingList;
	/**
	 * 
	 */
	public List<Trainer> trainers = new ArrayList<>();
	/**
	 * 
	 */
	public List<Client> clients = new ArrayList<>();

	/**
	 * 
	 */
	public void contactInfo() {
	}

	/**
	 * 
	 * @param trainer 
	 */
	public void assignTrainer(Trainer trainer) {
	}

	/**
	 * 
	 * @param trainingName 
	 */
	public void cancelTraining(Training trainingName) {
	}

	/**
	 * 
	 * @param trainingName 
	 */
	public void changeTraningDetails(Training trainingName) {
	}
}
