// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Manager {
	/**
	 * 
	 */
	private String managerName;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	private String phone;
	/**
	 * 
	 */
	private Training trainingList;
	/**
	 * 
	 */
	public Trainer[] trainer;
	/**
	 * 
	 */
	public Client[] client;

	/**
	 * 
	 */
	public void contactInfo() {
	}

	/**
	 * 
	 * @param trainer 
	 */
	public void assignTrainer(Trainer trainer) {
	}

	/**
	 * 
	 * @param trainingName 
	 */
	public void cancelTraining(Training trainingName) {
	}

	/**
	 * 
	 * @param trainingName 
	 */
	public void changeTraningDetails(Training trainingName) {
	}
}
