// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Training {
	/**
	 * 
	 */
	private String clientName;
	/**
	 * 
	 */
	private String eventName;
	/**
	 * 
	 */
	private String eventLocation;
	/**
	 * 
	 */
	private String eventDate;
	/**
	 * 
	 */
	private TrainingType eventType;
	/**
	 * 
	 */
	private String chapters;
	/**
	 * 
	 */
	private String trainerName;

	/**
	 * 
	 */
	public void trainingDetails() {
	}

	/**
	 * 
	 * @param date 
	 * @param location 
	 */
	public void modifyTrainingDetails(String date, String location) {
	}
}
