// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/************************************************************/
/**
 * 
 */
import java.util.*;
public class Trainer {
	/**
	 * 
	 */
	private String trainerName;
	/**
	 * 
	 */
	private String phone;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	public List<Training> trainings = new ArrayList<>();
	/**
	 * 
	 */

	public Trainer() {
	}

	public Trainer(String trainerName, String phone, String email){
		this.trainerName = trainerName;
		this.phone = phone;
		this.email = email;
	}

	/**
	 * 
	 */
	public void contactInfo() {
		System.out.println("Numele trainerului: " + this.trainerName + ", telefon: " + this.phone + ", adresa mail: " + this.email);
	}

	/**
	 * 
	 * @param date 
	 */
	public boolean checkAvalability(String date) {
		for(int i = 0; i < trainings.size(); i++){
			if(trainings.get(i).getEventDate().equalsIgnoreCase(date)){
				return false;
			}
		}
		return true;
	}

	/**
	 * 
	 * @param chapters 
	 * @param trainingType 
	 */
	public void addMaterials(List<String> chapters, String chapter) {
		chapters.add(chapter);
	}

	/**
	 * 
	 */
	public void checkSchedule() {
		for(int i = 0; i < trainings.size();i++){
			System.out.println(trainings.get(i).getEventDate());
		}
	}
}
