// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Trainer {
	/**
	 * 
	 */
	private String trainerName;
	/**
	 * 
	 */
	private String phone;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	private Training trainings;
	/**
	 * 
	 */
	public Training[] training;

	/**
	 * 
	 */
	public void contactInfo() {
	}

	/**
	 * 
	 * @param date 
	 */
	public void checkAvalability(String date) {
	}

	/**
	 * 
	 * @param chapters 
	 * @param trainingType 
	 */
	public void addMaterials(String chapters, TrainingType trainingType) {
	}

	/**
	 * 
	 */
	public void checkSchedule() {
	}
}
