// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public enum TrainingType {
	/**
	 * 
	 */
	PublicSpeaking,
	/**
	 * 
	 */
	WebDevelopment,
	/**
	 * 
	 */
	DataScience,
	/**
	 * 
	 */
	DataTransfer,
	/**
	 * 
	 */
	MachineLearning,
	/**
	 * 
	 */
	WorkPlaceEthics,
	/**
	 * 
	 */
	QualityAssurance,
	/**
	 * 
	 */
	Leadership,
	/**
	 * 
	 */
	Sales;
}
