// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/************************************************************/
/**
 * 
 */
import java.util.*;
public class Trainer {
	/**
	 * 
	 */
	private String trainerName;
	/**
	 * 
	 */
	private String phone;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	private Training trainings;
	/**
	 * 
	 */
	public Training[] training;

	public Trainer() {
	}

	/**
	 * 
	 */
	public void contactInfo() {
	}

	/**
	 * 
	 * @param date 
	 */
	public void checkAvalability(String date) {
	}

	/**
	 * 
	 * @param chapters 
	 * @param trainingType 
	 */
	public void addMaterials(List<String> chapters, TrainingType trainingType) {
	}

	/**
	 * 
	 */
	public void checkSchedule() {
	}
}
