// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
import java.util.*;

public class Client{

	private String clientName;
	private String phone;
	private String email;
	private Training trainingEvent = new Training();
	public List<Training> trainings = new ArrayList<>();

	Client(){}

	Client(String clientName, String phone, String email){
		this.clientName = clientName;
		this.phone = phone;
		this.email = email;
	}

	public void contactInfo() {
		System.out.println("Name: " + this.clientName);
		System.out.println("Phone: " + this.phone);
		System.out.println("Email: " + this.email);
	}


	public void cancelTraining(Manager manager, String eventName, String date) {
		for (Training training : this.trainings) {
			//if the training exists, request the manager to execute the cancellation
			if (training.getEventName().equals(eventName) && training.getEventDate().equals(date)) {
				//Am pus un obiect de tip manager pentru a putea elimina si din lista managerului
				manager.cancelTraining(training);
			} else {
				System.out.println("Could not cancel the training, as it doesn't exist. Please check the introduced training data.\n");
			}
		}
	}


	public void requestTraining( Manager manager,TrainingType trainingType, String trainingDate, String eventLocation, String eventName) {
		for (Trainer trainer : manager.trainers) {
			if(trainer.checkAvailability(trainingDate)){
				Training requestedTraining = new Training(this.clientName,trainer.getName(),eventName,eventLocation,trainingDate,trainingType);

				this.trainings.add(requestedTraining);
				manager.assignTrainer(trainer, requestedTraining);
			}
		}

	}

	public void changeTrainingDetails(Training trainingName) {
	}
}
