// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/************************************************************/
/**
 * 
 */
import java.util.*;
public class Trainer {
	/**
	 * 
	 */
	private String trainerName;
	/**
	 * 
	 */
	private String phone;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	public List<Training> trainings = new ArrayList<>();
	/**
	 * 
	 */
	private List<TrainingType> qualifications = new ArrayList<>();

	public Trainer() {
	}

	public Trainer(String trainerName, String phone, String email, List<TrainingType> qualifications){
		this.trainerName = trainerName;
		this.phone = phone;
		this.email = email;
		this.qualifications = qualifications;
	}

	/**
	 * 
	 */
	public void contactInfo() {
		System.out.println("Numele trainerului: " + this.trainerName + ", telefon: " + this.phone + ", adresa mail: " + this.email);
	}

	/**
	 * 
	 * @param date 
	 */
	public boolean checkAvalability(String date) {
		for(int i = 0; i < trainings.size(); i++){
			if(trainings.get(i).getEventDate().equalsIgnoreCase(date)){
				return false;
			}
		}
		return true;
	}

	/**
	 * 
	 * @param chapters 
	 * @param trainingType 
	 */
	public void addMaterials(String eventName, String chapter) {
		for(int i = 0; i < this.trainings.size(); i++){
			if(this.trainings.get(i).getEventName().equalsIgnoreCase(eventName)){
				this.trainings.get(i).insertChapter(chapter);
			}
		}
	}

	/**
	 * 
	 */
	public void checkSchedule() {
		for(int i = 0; i < trainings.size();i++){
			System.out.println(trainings.get(i).getEventDate());
		}
	}
}
