// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/************************************************************/
/**
 * 
 */
import java.util.*;
public class Trainer {

	private String trainerName;
	private String phone;
	private String email;
	public List<Training> trainings = new ArrayList<>();
	private List<TrainingType> qualifications = new ArrayList<>();

	public Trainer() {
	}

	public Trainer(String trainerName, String phone, String email, List<TrainingType> qualifications){
		this.trainerName = trainerName;
		this.phone = phone;
		this.email = email;
		this.qualifications = qualifications;
	}

	String getName(){
		return this.trainerName;
	}

	public void contactInfo() {
		System.out.println("Numele trainerului: " + this.trainerName + ", telefon: " + this.phone + ", adresa mail: " + this.email);
	}
	public boolean checkAvailability(String date) {
		for (Training training : trainings) {
			if (training.getEventDate().equalsIgnoreCase(date)) {
				return false;
			}
		}
		return true;
	}

	public void addMaterials(String eventName, String chapter) {
		for (Training training : this.trainings) {
			if (training.getEventName().equalsIgnoreCase(eventName)) {
				training.insertChapter(chapter);
			}
		}
	}

	public void checkSchedule() {
		for (Training training : trainings) {
			System.out.println(training.getEventDate());
		}
	}
}
