// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/************************************************************/
/**
 * 
 */
import java.util.*;
public class Trainer {

	private String trainerName;
	private String phone;
	private String email;
	public List<Training> trainings = new ArrayList<>();
	private List<TrainingType> qualifications = new ArrayList<>();

	public Trainer() {
	}

	public Trainer(String trainerName, String phone, String email, List<TrainingType> qualifications){
		this.trainerName = trainerName;
		this.phone = phone;
		this.email = email;
		this.qualifications = qualifications;
	}

	public String getTrainerName() {
		return trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public List<Training> getTrainings() {
		return trainings;
	}

	public void setTrainings(List<Training> trainings) {
		this.trainings = trainings;
	}

	public List<TrainingType> getQualifications() {
		return qualifications;
	}

	public void setQualifications(List<TrainingType> qualifications) {
		this.qualifications = qualifications;
	}

	public void contactInfo() {
		System.out.println("Numele trainer: " + this.trainerName);
		System.out.println("Telefon: " + this.phone);
		System.out.println("Adresa email: " + this.email);
	}
	public boolean checkAvailability(String date) {
		for (Training training : trainings) {
			if (training.getEventDate().equalsIgnoreCase(date)) {
				return false;
			}
		}
		return true;
	}

	public void addMaterials(String eventName, String chapter) {
		for (Training training : this.trainings) {
			if (training.getEventName().equalsIgnoreCase(eventName)) {
				training.insertChapter(chapter);
			}
		}
	}

	public void checkSchedule() {
		System.out.println("Date sustinere traininguri: ");
		for (Training training : trainings) {
			System.out.println(training.getEventDate());
		}
	}

	public boolean checkQualification(TrainingType trainingType){
		for(TrainingType type : this.qualifications){
			if(type == trainingType) return true;
		}
		return false;
	}
}
